name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '9.0' # Adjust this to match your .NET version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    # - name: Test
    #   run: dotnet test --no-restore --verbosity normal

    - name: Publish
      run: dotnet publish src/ProjectName.AppHost/ProjectName.AppHost.csproj -c Release -o ${{env.DOTNET_ROOT}}/projectname

    # Uncomment the following steps if you want to deploy to a hosting service like Azure, AWS, etc.
    # - name: Deploy to Azure Web App
    #   uses: azure/webapps-deploy@v2
    #   with:
    #     app-name: 'YourAzureWebAppName'
    #     publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
    #     package: '${{env.DOTNET_ROOT}}/projectname'

    # - name: Deploy to AWS
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #   run: |
    #     aws s3 sync ${{env.DOTNET_ROOT}}/projectname s3://your-bucket-name/

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: published-app
        path: ${{env.DOTNET_ROOT}}/projectname
